name: tdtime
description: "TD Time"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#com.hpace.tdtime
#ТД Время

version: 0.0.3+1
# изменить имя
# AndroidManifest.xml (located at android/app/src/main
# <application android:label="App Name" ...>
# info.plist (located at ios/Runner)
# <key>CFBundleDisplayName</key>
# <string>App Name</string>

#обязательно для удаления очищения данных
# <application android:allowBackup="false"
# в файле AndroidManifest.xml

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 
  flutter_bloc: ^8.1.6 #https://pub.dev/packages/flutter_bloc
  bloc: ^8.1.4 #https://pub.dev/packages/bloc
  equatable: ^2.0.5 #https://pub.dev/packages/equatable
  page_transition: ^2.1.0 #https://pub.dev/packages/page_transition
  shared_preferences: ^2.3.2 #https://pub.dev/packages/shared_preferences
  flutter_launcher_icons: ^0.13.1 #https://pub.dev/packages/flutter_launcher_icons
  go_router: ^14.2.7 #https://pub.dev/packages/go_router
  get: ^4.6.6 #https://pub.dev/packages/get
  dio: ^5.7.0 #https://pub.dev/packages/dio
  gap: ^3.0.1 #https://pub.dev/packages/gap
  intl: ^0.19.0 #https://pub.dev/packages/intl
  path_provider: ^2.1.4 #https://pub.dev/packages/path_provider
  fullscreen_window: ^1.1.0 # https://pub.dev/packages/fullscreen_window
  open_file: ^3.5.5 # https://pub.dev/packages/open_file
  flutter_easylogger: ^2.3.3 #https://pub.dev/packages/flutter_easylogger
  flutter_svg: ^2.0.10+1 #https://pub.dev/packages/flutter_svg
  package_info_plus: ^8.0.2 #https://pub.dev/packages/package_info_plus/install
  qr_code_scanner: ^1.0.1 #https://pub.dev/packages/qr_code_scanner
  geolocator: ^13.0.1 #https://pub.dev/packages/geolocator
  ftpconnect: ^2.0.7 #https://pub.dev/packages/ftpconnect
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

dependency_overrides:
    flutter_lints: ^2.0.1
    http: ^1.0.0
    intl: ^0.18.1
    win32: ^5.5.4
    archive: ^3.6.1


# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: ic_launcher
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
